### ISSUE TITLE
Migrate some State for some screens from their composables  to their respective ViewModels

### ISSUE THREAD

**Issue by chege4179** [droidconKE/droidconKE2023Android#111]
There are some screens like the SpeakersScreen where the speakers state variable is in the composable,i.e 
```
val speakers = remember { mutableStateListOf<SpeakerUI>() }
LaunchedEffect(Unit) {
       speakers.addAll(speakersViewModel.getSpeakers())
 } 

```
then the speakers are loaded into the state using the LaunchedEffect block. I was suggesting if we could migrate the state from the composable to the view model and load it from there. Same thing with the SpeakerDetailsScreens and others

**Comment by wangerekaharun** [comment]
Sur, @chege4179 thanks for flagging this! Feel free to pick it up

**Comment by chege4179** [comment]
Ok I'll take it up
