### ISSUE TITLE
[Fix Emojis] in the feedback section 

### ISSUE THREAD

**Issue by josphatmwania** [droidconKE/droidconKE2023Android#136]
**A clear and concise description of what the bug is.**
The feedback emojis show the same feeling for Okay, Great, and Bad.

**Expected behavior**
Show different feelings for satisfaction.

**Screenshots**
EXPECTED
![image](https://github.com/droidconKE/droidconKE2023Android/assets/82445335/a858fd99-9b1d-4640-a781-bce2b880066f)

ACTUAL
![image](https://github.com/droidconKE/droidconKE2023Android/assets/82445335/dfdb8a3b-bc4f-48e6-b0fe-29cfdf3e4801)

**Comment by chepsi** [comment]
@josphatmwania assigned to you
