### ISSUE TITLE
[Fix About Us] Text colour not clear in dark mode

### ISSUE THREAD

**Issue by misshannah** [droidconKE/droidconKE2023Android#137]
**Describe the bug**
Some of the text in the about screen is not visible in dark theme mode

**To Reproduce**
1. Change device settings to dark theme before opening the app 
2. Go to 'About'
3. See unreadable sections in screen

**Expected behavior**
Readable text

**Screenshots**
Added screenshot
![Screenshot_20230614-222208](https://github.com/droidconKE/droidconKE2023Android/assets/5990196/008bbabf-c278-4f29-97f5-930ecc5a72fa)

**Comment by Borwe** [comment]
I have sent PR. :)
