### ISSUE TITLE
[Fix Preview] Presentation Module - Feed screen not visible

### ISSUE THREAD

**Issue by misshannah** [droidconKE/droidconKE2023Android#152]
**Describe the bug**
In the presentation Module, one can't see a preview of the Feed screen in the IDE

**To Reproduce**
Refer to the screenshot below.

**Expected behavior**
A preview of the feed screen in the IDE

**Screenshots**
<img width="1406" alt="Screenshot 2023-07-25 at 15 30 01" src="https://github.com/droidconKE/droidconKE2023Android/assets/5990196/744cecd5-83cf-4ba9-8754-5aac34377222">

**Comment by yveskalume** [comment]
Can I take this one @wangerekaharun

**Comment by chepsi** [comment]
Absolutely @yveskalume, let me assign it to you
