### ISSUE TITLE
Re-Introduce Feed Tab

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKE2023Android#17]
Ths was removed since the API didn't have any data. We should re-add it and add API implementation.

**Comment by yveskalume** [comment]
I'd like to take this, but I don't know how I can access data, since I don't have an API key. Perhaps we can have a mock webserver.

**Comment by wangerekaharun** [comment]
> I'd like to take this, but I don't know how I can access data, since I don't have an API key. Perhaps we can have a mock webserver.

Okay, on a separate note, the API key doesn't affect development in any layer since it only affects them items not displaying. We already have tests + for all APIs in place

**Comment by yveskalume** [comment]
What's the endpoint for Feed, I have not seen either the Feed entity

**Comment by wangerekaharun** [comment]
> What's the endpoint for Feed, I have not seen either any FeedItem entity

You can do the UI bit since the design is already there, it's just re-adding the tab to the navigation graph. We'll have a separate ticket to do the API bit
