### ISSUE TITLE
ScrollAppBarBehaviour on FeedbackScreen

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKE2023Android#29]
Based on the design of the FeedbackScreen, we want to have a collapsible top app bar.

**Comment by chepsi** [comment]
[This article](https://www.droidcon.com/2022/12/19/creating-a-collapsing-topappbar-with-jetpack-compose/) might be a good guide

**Comment by Joel-K-Muraguri** [comment]
Can I take this up?

**Comment by wangerekaharun** [comment]
> Can I take this up?

Sure feel free,I have assigned you the issue
