### ISSUE TITLE
Add Chucker For Easy Debugging of Network Requests

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2023Android#38]

**Comment by wangerekaharun** [comment]
> Are there any other alternatives to chucker we can explore?

Haven't heard of any

**Comment by yveskalume** [comment]
can i take this ?

**Comment by wangerekaharun** [comment]
> can i take this ?

Sure feel free, I've assigned you the ticket

**Comment by yveskalume** [comment]
Thanks @wangerekaharun 

I've read that Chucker works with Ktor only when OkHttp engine is used.
