### ISSUE TITLE
Document api_key setup steps on readme

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2023Android#39]

**Comment by chege4179** [comment]
@wangerekaharun  can you show me how to get the API KEY so I can set up it and also include it in the README.md since the API requests are failing because of the API KEY  when I build the app

**Comment by wangerekaharun** [comment]
> @wangerekaharun can you show me how to get the API KEY so I can set up it and also include it in the README.md since the API requests are failing because of the API KEY when I build the app

will work on a fix for this

**Comment by chege4179** [comment]
ok

**Comment by misshannah** [comment]
Hello @chege4179 I'm working on setting this up. I'll update you when it's done.

**Comment by chege4179** [comment]
Ok
