### ISSUE TITLE
Use buttons from Chai

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKE2023Android#47]
Refactor the codebase to use buttons in the Design System(Chai). Buttons are currently present in;
1. https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1ef2f9cd-d83b-4618-8f29-655f3a9483ae/
2. https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/09ac0874-4933-4982-9e2e-b5d2c82d6c5f/
3. https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/8eef15fe-3d82-4c60-b9a1-f0b436119f7a/

**Comment by Jacquigee** [comment]
I'd like to take this up

**Comment by wangerekaharun** [comment]
> I'd like to take this up

Sure fell free, I've assigned you the ticket

**Comment by Jacquigee** [comment]
Thanks
