### ISSUE TITLE
Use StateFlow to hold UI Data

### ISSUE THREAD

**Issue by BKinya** [droidconKE/droidconKE2023Android#60]
Currently, the app uses both `StateFlow`(check `SpeakersViewModel` ) and `LiveData`(Check `SessionsViewModel`) to hold UI data. 

LiveData is officially deprecated, Check this [reddit](https://www.reddit.com/r/mAndroidDev/comments/mcfl9n/livedata_is_officially_deprecated_in_kotlinonly/)

 Solution: migrate current implementations to use Stateflow and take advantage of the features of Kotlin Flows

**Comment by wangerekaharun** [comment]
Great catch @BKinya, will remove all assignees so that anyone can feel free to pick this up

**Comment by wangerekaharun** [comment]
> @wangerekaharun Can I take this up

Sure
