### ISSUE TITLE
[Document] List of feature that need support 

### ISSUE THREAD

**Issue by mohit-sharma-87** [droidconKE/droidconKE2023Android#7]
I would like to contribute to the app but don't know where to start as there is no list of features pending for implementation.

**Comment by wangerekaharun** [comment]
Sure @mohit-sharma-87 we're working on having the updated list of things needed to be worked on

**Comment by wangerekaharun** [comment]
@mohit-sharma-87 We added some issues over the weekend, feel free to pick one, and incase anything is not clear we're happy to answer questions.
