### ISSUE TITLE
Use a Date Format that doesn't Require Build.VERSION_CODES.O

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2023Android#92]
`EventDate` uses `LocalDate` that uses Build.VERSION_CODES.O, which forces all files using this class to have a `@RequiresApi(Build.VERSION_CODES.O)` annotation. We should find a format that doesn't need this

**Comment by joenjogu** [comment]
Hi @wangerekaharun .
I'd like to pick this up.
Kindly assign this to me.

**Comment by joenjogu** [comment]
@wangerekaharun @chepsi @jumaallan I have a working fix for this. Kindly assign me the issue.

**Comment by wangerekaharun** [comment]
> @wangerekaharun @chepsi @jumaallan I have a working fix for this. Kindly assign me the issue.

done
