### ISSUE TITLE
Add fetch Feed from API implementation

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2023Android#94]
This was done in last year's app but not merged, so you can borrow the logic [here](https://github.com/droidconKE/droidconKE2022Android/pull/168)

**Comment by Jacquigee** [comment]
Please assign this issue to me.

**Comment by wangerekaharun** [comment]
> Please assign this issue to me.

Sure I have assigned you the issue

**Comment by Jacquigee** [comment]
Thanks

**Comment by wangerekaharun** [comment]
@Jacquigee hey, any updates on this?

**Comment by Jacquigee** [comment]
@wangerekaharun can I give you an update before the month ends?
